/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.table.view;

import java.awt.BorderLayout;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;

import controller.Controller;
import controller.VehiclesController;
import model.ParkingLogic;
import model.dao.ParkingLotDao;
import model.entity.ParkingLot;
import view.table.model.GestionTableHeader;
import view.table.model.TableModel;
import view.components.DetailPanel;
import view.table.model.CellsGestion;

/**
 *
 * @author conde
 */
public class TablePanel extends javax.swing.JPanel {
	
	private Controller controller;
	public final int SPOTS_NUMBER = 16;
	private static TablePanel tablePanel;

	private TablePanel() {
		initComponents();

	}

	public static TablePanel getInstance() {

		if (tablePanel == null) {
			tablePanel = new TablePanel();
		}

		return tablePanel;
	}
	
	
	public void setController(Controller controller) {
		this.controller = controller;
	}
	
	

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		parkedVehiclesTable = new javax.swing.JTable();

		setBackground(new java.awt.Color(240, 240, 240));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout
						.createSequentialGroup().addGap(62, 62, 62).addComponent(jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(68, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout
						.createSequentialGroup().addGap(52, 52, 52).addComponent(jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(72, Short.MAX_VALUE)));
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable parkedVehiclesTable;
	// End of variables declaration//GEN-END:variables

	public void buildTable() {
		String titles[] = { "Lugar", "Vehiculo", "Patente", "Fecha de Admision", "Hora de Ingreso" };
		String data[][] = getMatriz();
		TableModel tableModel = new TableModel(data, titles);
		parkedVehiclesTable.setModel(tableModel);

		// personaliza el encabezado
		JTableHeader jtableHeader = parkedVehiclesTable.getTableHeader();
		jtableHeader.setDefaultRenderer(new GestionTableHeader());
		parkedVehiclesTable.setTableHeader(jtableHeader);

		parkedVehiclesTable.setRowHeight(30);
		parkedVehiclesTable.getColumnModel().getColumn(0).setMaxWidth(62);
		parkedVehiclesTable.getColumnModel().getColumn(1).setPreferredWidth(92);
		parkedVehiclesTable.getColumnModel().getColumn(2).setPreferredWidth(92);
		parkedVehiclesTable.getColumnModel().getColumn(3).setPreferredWidth(92);
		parkedVehiclesTable.getColumnModel().getColumn(4).setPreferredWidth(92);

		parkedVehiclesTable.getColumnModel().getColumn(0).setCellRenderer(new CellsGestion("spot"));
		parkedVehiclesTable.getColumnModel().getColumn(1).setCellRenderer(new CellsGestion("vehicle"));
		parkedVehiclesTable.getColumnModel().getColumn(2).setCellRenderer(new CellsGestion("spot"));
		parkedVehiclesTable.getColumnModel().getColumn(3).setCellRenderer(new CellsGestion("plain"));
		parkedVehiclesTable.getColumnModel().getColumn(4).setCellRenderer(new CellsGestion("plain"));

		parkedVehiclesTable.setGridColor(new java.awt.Color(0, 0, 0));
		parkedVehiclesTable.setShowHorizontalLines(true);
		parkedVehiclesTable.setShowVerticalLines(true);

		jScrollPane1.setViewportView(parkedVehiclesTable);
	}

	private String[][] getMatriz() {
		
		controller.setParkingLots(null);
		ArrayList<ParkingLot> parkingLots = controller.getParkingLots();
		
		
		String matrizData[][] = new String[SPOTS_NUMBER][5];
		for(int i = 0; i < parkingLots.size(); i++) {
			matrizData[i][0]=parkingLots.get(i).getSpot() + "";
			matrizData[i][1]=parkingLots.get(i).getVehicle();
			matrizData[i][2]=parkingLots.get(i).getPlate();
			matrizData[i][3]=parkingLots.get(i).getAdmissionDate();
			matrizData[i][4]=parkingLots.get(i).getAdmissionHour();
		}
		
		
		return matrizData;
	}
}
