/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.frames;

/**
 *
 * @author conde
 */
public class GetPaidDialog extends javax.swing.JDialog {

    /**
     * Creates new form TicketCollectDialog
     */
    public GetPaidDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setTitle("Cobrar");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGetPaid = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailTextArea = new javax.swing.JTextArea();
        addDiscountLbl = new javax.swing.JLabel();
        discountNumberTextField = new javax.swing.JTextField();
        percentLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnGetPaid.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnGetPaid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/cashier_icon.png"))); // NOI18N
        btnGetPaid.setText("Cobrar");

        detailTextArea.setColumns(20);
        detailTextArea.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        detailTextArea.setRows(5);
        jScrollPane1.setViewportView(detailTextArea);

        addDiscountLbl.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        addDiscountLbl.setText("Agregar descuento:");

        discountNumberTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        discountNumberTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        discountNumberTextField.setText("0.00");

        percentLbl.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        percentLbl.setText("%");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 138, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnGetPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addDiscountLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(discountNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(percentLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(discountNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addDiscountLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(percentLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btnGetPaid)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addDiscountLbl;
    private javax.swing.JButton btnGetPaid;
    private javax.swing.JTextArea detailTextArea;
    private javax.swing.JTextField discountNumberTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel percentLbl;
    // End of variables declaration//GEN-END:variables
}
