/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.frames;

import controller.Controller;
import model.privileges.Privileges;

/**
 *
 * @author conde
 */
public class ReportsDialog extends javax.swing.JDialog {


	private static ReportsDialog reportsDialog;
	private Controller controller;
	
    private ReportsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public static ReportsDialog getInstance(java.awt.Frame parent, boolean modal) {
    	
    	if(reportsDialog == null) {
    		reportsDialog = new ReportsDialog(parent, modal);
    	}
    	
    	return reportsDialog;
    }
    
	public void setController(Controller controller) {
		this.controller = controller;
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPaneReports = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vehiclesEntryTxtArea = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        cashRegisterCollectionTxtArea = new javax.swing.JTextArea();
        btnSaveFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabbedPaneReports.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        vehiclesEntryTxtArea.setBackground(new java.awt.Color(44, 47, 51));
        vehiclesEntryTxtArea.setColumns(20);
        vehiclesEntryTxtArea.setForeground(new java.awt.Color(255, 255, 255));
        vehiclesEntryTxtArea.setRows(5);
        jScrollPane1.setViewportView(vehiclesEntryTxtArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE))
        );

        tabbedPaneReports.addTab("Entrada y salida de vehiculos", jPanel1);

        cashRegisterCollectionTxtArea.setBackground(new java.awt.Color(44, 47, 51));
        cashRegisterCollectionTxtArea.setColumns(20);
        cashRegisterCollectionTxtArea.setForeground(new java.awt.Color(255, 255, 255));
        cashRegisterCollectionTxtArea.setRows(5);
        jScrollPane3.setViewportView(cashRegisterCollectionTxtArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE))
        );

        tabbedPaneReports.addTab("Recaudacion de caja", jPanel2);

        btnSaveFile.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnSaveFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/save_file_icon.png"))); // NOI18N
        btnSaveFile.setText("  Archivar  ");
        btnSaveFile.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSaveFile)
                    .addComponent(tabbedPaneReports, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPaneReports, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSaveFile)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveFile;
    private javax.swing.JTextArea cashRegisterCollectionTxtArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane tabbedPaneReports;
    private javax.swing.JTextArea vehiclesEntryTxtArea;
    // End of variables declaration//GEN-END:variables

	public void setPrivileges(String userName) {
		if (userName.equals(Privileges.ADMINISTRATOR.toString().toLowerCase())) {

			btnSaveFile.setEnabled(true);

		} else if (userName.equals(Privileges.USER.toString().toLowerCase())) {

			btnSaveFile.setEnabled(false);

		}
		
	}

}
